-- ════════════════════════════════════════════════════════════════════════════
--  0002：插入顺序列 seq
--
--  背景
--    业务代码用"插入顺序"表达稳定次序，共 3 种用法：
--      * ORDER BY seq                  导出/列表的稳定顺序
--      * ORDER BY created_at, seq      created_at 并列时的确定性消解
--      * ORDER BY seq DESC LIMIT 1     "最新插入的一条"
--
--    PostgreSQL 没有可依赖的隐式行序。ctid 不能用：它标识物理位置，UPDATE
--    之后会变，而"插入顺序"必须在行被更新后保持不变（本体操作/审核决定虽为
--    INSERT-only，但 drafts 等表会更新）。因此必须显式补一列 seq。
--
--  为什么是 BY DEFAULT 而不是 GENERATED ALWAYS
--    `Repository.import_projection` 会按"导出载荷里出现、且表里存在"的列
--    **动态拼 INSERT**。若某次导出带上了 seq，GENERATED ALWAYS 会直接报错；
--    BY DEFAULT 允许显式值，兼容该路径。
--
--  这是**有意新增的 schema 元素**
--    插入顺序无法由任何隐式物理属性表达，只能在 PG 侧以显式列补出该语义。
--    测试 test_postgres_schema.py 会正向断言这 7 张表的 seq 都是 BY DEFAULT
--    IDENTITY 且带 (project_id,..,seq) 索引，防止被误删。
-- ════════════════════════════════════════════════════════════════════════════

-- 制品：无任何时间戳列，插入顺序是唯一的"先后"信号
ALTER TABLE artifacts
    ADD COLUMN seq bigint GENERATED BY DEFAULT AS IDENTITY;

-- 本体快照：ORDER BY seq DESC LIMIT 1 取"最新发布的那个本体"
ALTER TABLE ontologies
    ADD COLUMN seq bigint GENERATED BY DEFAULT AS IDENTITY;

-- 断言事件：ORDER BY created_at, seq —— seq 用于并列消解
ALTER TABLE assertion_events
    ADD COLUMN seq bigint GENERATED BY DEFAULT AS IDENTITY;

-- 本体草稿 / 操作 / 审核决定：导出与列表都按插入顺序
ALTER TABLE ontology_drafts
    ADD COLUMN seq bigint GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE ontology_operations
    ADD COLUMN seq bigint GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE ontology_review_decisions
    ADD COLUMN seq bigint GENERATED BY DEFAULT AS IDENTITY;

-- 合并操作：ORDER BY created_at, seq
ALTER TABLE merge_operations
    ADD COLUMN seq bigint GENERATED BY DEFAULT AS IDENTITY;

-- ════════════════════════════════════════════════════════════════════════════
--  索引：让 ORDER BY seq 不必排序整表
-- ════════════════════════════════════════════════════════════════════════════

-- artifacts 的两种读取形态：按项目列出、按 kind(+项目) 取最新
CREATE INDEX artifacts_project_seq ON artifacts (project_id, seq);
CREATE INDEX artifacts_kind_project_seq ON artifacts (kind, project_id, seq);

CREATE INDEX ontologies_project_seq ON ontologies (project_id, seq);

CREATE INDEX assertion_events_project_created_seq
    ON assertion_events (project_id, created_at, seq);

CREATE INDEX ontology_drafts_project_seq ON ontology_drafts (project_id, seq);
CREATE INDEX ontology_operations_project_seq ON ontology_operations (project_id, seq);
CREATE INDEX ontology_review_decisions_project_seq
    ON ontology_review_decisions (project_id, seq);

CREATE INDEX merge_operations_project_created_seq
    ON merge_operations (project_id, created_at, seq);
