(function(root){
  const groups=[['entity_types','实体类'],['relation_types','关系'],['attributes','属性']];
  function shortIri(value){const iri=String(value??''),delimiter=Math.max(iri.lastIndexOf('#'),iri.lastIndexOf('/'),iri.lastIndexOf(':')),terminal=iri.slice(delimiter+1);if(!terminal)return {label:iri,malformed:false,raw:iri};try{return {label:decodeURIComponent(terminal),malformed:false,raw:iri};}catch{return {label:terminal,malformed:true,raw:iri};}}
  function nameOf(item){return item?.label_zh||item?.label||item?.name||'未命名术语';}
  function indexTerms(summary={}){const index=new Map();for(const kind of ['classes','relations','attributes'])for(const item of summary[kind]||[]){index.set(item.id,nameOf(item));index.set(item.name,nameOf(item));}return index;}
  function refs(values,index){return values?.length?values.map(value=>index.get(value)||shortIri(value).label).join('、'):'未指定';}
  function json(value){return JSON.stringify(value||{},null,2);}
  function copyButton(kind,label,key=''){return `<button type="button" class="ontology-copy" data-copy-kind="${kind}"${key?` data-copy-key="${key}"`:''} aria-label="复制${label}">复制</button>`;}
  function readableOntology(draft,esc){const summary=draft.schema_summary||draft.summary||{},index=indexTerms(summary),cards=[];for(const item of summary.classes||[])cards.push(`<article><span>实体类</span><b>${esc(nameOf(item))}</b><p>${esc(item.description||'暂无定义，请在发布前补充')}</p><small>父类：${esc(refs(item.parents,index))}</small></article>`);for(const item of summary.relations||[])cards.push(`<article><span>关系</span><b>${esc(nameOf(item))}</b><p>${esc(item.description||'暂无定义，请在发布前补充')}</p><small>起点类型：${esc(refs(item.domain,index))}<br>终点类型：${esc(refs(item.range,index))}</small></article>`);for(const item of summary.attributes||[])cards.push(`<article><span>属性</span><b>${esc(nameOf(item))}</b><p>${esc(item.description||'暂无定义，请在发布前补充')}</p><small>适用实体：${esc(refs(item.domain,index))}<br>数据类型：${esc(refs(item.range,index))}</small></article>`);return cards.join('')||'<p class="subtle">草案中没有可展示的本体术语</p>';}
  function readableDiff(diff={},esc){const labels={added:'新增',retained:'保留',removed:'删除'},items=[];for(const [group,title] of [['classes','实体类'],['relations','关系'],['attributes','属性']])for(const state of ['added','retained','removed']){const rows=diff[group]?.[state]||[];if(rows.length)items.push(`<div><b>${title} · ${labels[state]}</b><p>${rows.map(row=>esc(row.label||row.name||shortIri(row.id||row).label)).join('、')}</p></div>`);}return items.join('')||'<p class="subtle">没有可展示的版本变化。</p>';}
  function readableMappings(mappings={},esc){const rows=[];for(const [key,title] of groups)for(const [name,iri] of Object.entries(mappings[key]||{})){const shown=shortIri(iri);rows.push(`<div class="ontology-mapping-row"><span>${esc(title)}</span><b>${esc(name)}</b><i>→</i><code>${esc(shown.label)}</code>${shown.malformed?'<em class="ontology-encoding-warning">编码格式不完整</em>':''}<details><summary>查看完整技术标识</summary><code>${esc(iri)}</code>${copyButton('iri','完整 IRI',esc(`${key}:${name}`))}</details></div>`);}return rows.join('')||'<p class="subtle">没有名称映射。</p>';}
  function renderTechnicalDetails(draft={},esc=value=>String(value)){const suffix=String(draft.id||'draft').replace(/[^\w-]/g,'');return `<details class="ontology-technical-details"><summary>查看版本变化与技术详情</summary><div class="ontology-detail-region" aria-describedby="diff-help-${suffix}"><h5>版本差异</h5><p id="diff-help-${suffix}">展示本草案相对上一版新增、保留或删除的实体类、关系和属性。第一版草案会把全部术语显示为新增。</p><div class="ontology-readable-grid">${readableDiff(draft.diff,esc)}</div><details><summary>查看原始数据</summary>${copyButton('diff','原始差异数据')}<pre>${esc(json(draft.diff))}</pre></details></div><div class="ontology-detail-region" aria-describedby="turtle-help-${suffix}"><h5>本体定义</h5><p id="turtle-help-${suffix}">本体定义规定系统认识哪些事物、它们可以建立什么关系，以及可使用哪些属性。系统以 Turtle 标准格式保存。</p><div class="ontology-readable-grid">${readableOntology(draft,esc)}</div><details><summary>查看 Turtle 原始源码</summary>${copyButton('turtle','Turtle 原始源码')}<pre>${esc(draft.turtle||'')}</pre></details></div><div class="ontology-detail-region" aria-describedby="mapping-help-${suffix}"><h5>名称与技术标识</h5><p id="mapping-help-${suffix}">每个中文名称都对应一个唯一 IRI，供系统稳定引用。%E4%... 是中文经过 URI 编码后的技术表示，不是乱码，日常使用无需处理。</p><div class="ontology-mappings">${readableMappings(draft.mappings,esc)}</div><details><summary>查看原始映射数据</summary>${copyButton('mappings','原始映射数据')}<pre>${esc(json(draft.mappings))}</pre></details></div><div class="ontology-copy-status" role="status" aria-live="polite"></div></details>`;}
  function bindCopyButtons(host,draft={},clipboard=root.navigator?.clipboard){const status=host.querySelector('.ontology-copy-status');host.querySelectorAll('[data-copy-kind]').forEach(button=>button.onclick=async()=>{const kind=button.dataset.copyKind,key=button.dataset.copyKey;let value=kind==='turtle'?(draft.turtle||''):kind==='diff'?json(draft.diff):kind==='mappings'?json(draft.mappings):'';if(kind==='iri'){const split=key.indexOf(':'),group=key.slice(0,split),name=key.slice(split+1);value=draft.mappings?.[group]?.[name]||'';}try{if(!clipboard?.writeText)throw Error('clipboard unavailable');await clipboard.writeText(value);button.textContent='已复制';status.textContent='已复制';root.setTimeout(()=>button.textContent='复制',2000);}catch{status.textContent='复制失败，请手动选择内容';}});}
  const api={shortIri,nameOf,indexTerms,refs,renderTechnicalDetails,bindCopyButtons};root.OntologyDetails=api;if(typeof module!=='undefined')module.exports=api;
})(globalThis);
